version: "2"
services:
  webapp:
    container_name: php-webapp
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      # 特に必要ないが設定(参考)
      TZ: "Asia/Tokyo"
    # systemctlの有効化
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    ports:
      - "8080:80"
      - "9011:9001"
      - "22011:22"
    volumes:
      - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./conf/php/0100-custom-settings.ini:/etc/php.d/0100-custom-settings.ini"
      - "./src/:/var/www/app/public"
